stages:
  - build
  - deploy

jupyter-build:
  stage: build
  image: python:slim
  script:
    - pip install -U jupyter-book
    - jupyter-book clean documentation
    - jupyter-book build documentation
  artifacts:
    paths:
      - documentation/_build/
  rules:
    - if: $CI_COMMIT_BRANCH == "gl-pages"

pages:
  stage: deploy
  image: busybox:latest
  script:
    - mv documentation/_build/html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "gl-pages"
