version: '3.6'

services:
  owler:
    build:
      context: .
      dockerfile: Dockerfile.owler
      args:
        TAG: frue_ra_owler
    user: "${MY_UID}:${MY_GID}"
    container_name: frue_ra_owler
    networks:
      - frue_ra_storm_network
    volumes:
      - ${INPUT:-./input}:/data/input
      - ./external/storm/log4j2:/apache-storm-2.4.0/log4j2
      - maven-repo:/localdata1/frue_ra/.m2
      - ./logs:/loginternal
      - ${OUTPUT:-./output}:/outdata
      - ./src/main/resources/dataset:/resources
    restart: "no"
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  frue_ra_storm_network:
    external: true

volumes:
  maven-repo: