FROM python:3.8

WORKDIR /app

COPY lof_api.py /app
# COPY data/model/corpus_embedding_d_0_rp.hdf5 /app/data/model/corpus_embedding.hdf5
# COPY data/model/filtered_bert_embeddings.hdf5 /app/data/model/corpus_embedding.hdf5
COPY data/model/corpus_embedding_d_0_rp_nochunk.hdf5 /app/data/model/corpus_embedding.hdf5

RUN pip install scikit-learn numpy h5py flask

EXPOSE 43044

CMD ["python3", "lof_api.py"]
