version: "3.6"

services:

  frontier:
    networks:
      - frue_ra_storm_network
    build:
      context: ../url-frontier/
      dockerfile: Dockerfile
    environment:
      URLFRONTIER_HOST: "0.0.0.0"
      URLFRONTIER_PORT: "7071"
    image: crawlercommons/url-frontier
    container_name: frue_ra_frontier
    hostname: frue-ra-frontier
    ports:
      - 7071:7071
      - 43002:43002
    extra_hosts:
      - "host.docker.internal:host-gateway"

#   prometheus:
#     image: prom/prometheus
#     container_name: prometheus
#     ports:
#       - "9090:9090"
#     volumes:
#       - /home/lobster/Desktop/Projects/url-frontier/service/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
#     command:
#       - '--config.file=/etc/prometheus/prometheus.yml'
#     networks:
#       - frue_ra_storm_network

  # grafana:
  #   image: grafana/grafana:8.3.5
  #   container_name: grafana
  #   volumes:
  #     - /home/lobster/Desktop/Projects/url-frontier/service/monitoring/:/etc/grafana/provisioning/
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - frue_ra_storm_network

  # loki:
  #   image: grafana/loki:2.4.2
  #   container_name: loki
  #   volumes:
  #     - /home/lobster/Desktop/Projects/url-frontier/service/monitoring/local-config.yml:/etc/loki/local-config.yaml
  #   ports:
  #     - "127.0.0.1:3100:3100"
  #   command: -config.file=/etc/loki/local-config.yaml
  #   networks:
  #     - frue_ra_storm_network

  # Apache Storm components
  # - Zookeeper coordinates the communication between Nimbus and the Supervisors
  zookeeper:
    networks:
      - frue_ra_storm_network
    image: zookeeper:${ZOOKEEPER_VERSION:-3.6.3}
    container_name: frue_ra_zookeeper
    ports:
      - 43004:43004
    restart: always

  # - the daemon Nimbus runs on the master node
  storm-nimbus:
    networks:
      - frue_ra_storm_network
    image: storm:${STORM_VERSION:-2.4.0}
    container_name: frue_ra_storm-nimbus
    ## must override worker.childopts and remove options not available
    ## for Java 11: `-XX:+PrintGCDateStamps`, etc#
    hostname: nimbus
    command: storm nimbus
        -c worker.childopts="-Xmx%HEAP-MEM%m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=artifacts/heapdump"
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - 43003:43003
    external_links:
      - zookeeper
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway

  # - the Supervisors run on the worker nodes
  storm-supervisor:
    networks:
      - frue_ra_storm_network
    image: storm:${STORM_VERSION:-2.4.0}
    container_name: frue_ra_storm-supervisor
    ## must override worker.childopts and remove options not available
    ## for Java 11: `-XX:+PrintGCDateStamps`, etc
    command: storm supervisor
        -c worker.childopts="-Xmx%HEAP-MEM%m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=artifacts/heapdump"
    depends_on:
      - zookeeper
      - storm-nimbus
    links:
      - zookeeper
      - storm-nimbus:nimbus
    volumes:
      - ${INPUT:-./input}:/data/input
      - ${LOGS:-./logs}:/logs
      - ./external/storm/log4j2:/apache-storm-2.4.0/log4j2
      - ./model:/data/model
      - ./data/model:/bert/model
      - ./data:/data
      - ${OUTPUT:-./output}:/outdata
      - ./src/main/resources/dataset:/resources
    external_links:
      - zookeeper
    restart: always
    cap_add:
      - NET_ADMIN
    extra_hosts:
      - host.docker.internal:host-gateway

  # - the Storm UI provides diagnostics about the Storm cluster
  storm-ui:
    networks:
      - frue_ra_storm_network
    image: storm:${STORM_VERSION:-2.4.0}
    container_name: frue_ra_storm-ui
    command: storm ui
    depends_on:
      - storm-nimbus
    links:
      - storm-nimbus:nimbus
    ports:
      - 43043:43043
    external_links:
      - zookeeper
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway

  # - to launch a topology
  # - will exit on startup - not anymore
  # build owler image: docker build --tag frue_ra_owler:0.1-SNAPSHOT .

  owler:
    build:
      context: .
      dockerfile: Dockerfile.owler
      args:
        TAG: frue_ra_owler
    user: "${MY_UID}:${MY_GID}"
    container_name: frue_ra_owler
    depends_on:
      - storm-nimbus
      - frontier
      - lof-service
      - redis
    networks:
      - frue_ra_storm_network
    volumes:
      - ${INPUT:-./input}:/data/input
      - ./external/storm/log4j2:/apache-storm-2.4.0/log4j2
      - maven-repo:/localdata1/frue_ra/.m2
      - ./logs:/loginternal
      - ${OUTPUT:-./output}:/outdata
      - ./src/main/resources/dataset:/resources
    restart: "no"
    extra_hosts:
      - host.docker.internal:host-gateway

  lof-service:
    build:
      context: .
      dockerfile: Dockerfile.lof
    container_name: frue_ra_lof
    networks:
      - frue_ra_storm_network
    ports:
      - 43044:43044

  redis:
    image: redis:latest
    container_name: frue_ra_redis
    networks:
      - frue_ra_storm_network
    ports:
      - 6379:6379
    restart: always

  tfidf-api:
    build:
      context: .
      dockerfile: Dockerfile.tfidf
    container_name: flask_tfidf_api
    networks:
      - frue_ra_storm_network
    ports:
      - 5000:5000

networks:
  frue_ra_storm_network:
    driver: bridge

volumes:
  maven-repo:
