#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : # The title of the book. Will be placed in the left navbar.
author                      : University of Passau  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : images/logo.png  # A path to the book logo

html:
  favicon: images/favicon.png
  extra_navbar: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true


repository:
  url: https://opencode.it4i.eu/openwebsearcheu/
  branch: master

bibtex_bibfiles:
   - references.bib